### ISSUE TITLE
Create v0.0.6 git version tag

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polytool#31]
In the package.json, we have `0.0.6`, but the last git tag (and npm version) is the `v0.0.5`.

**Comment by justinfagnani** [comment]
Fixed!

**Comment by abdonrd** [comment]
Thanks! :)

**Comment by abdonrd** [comment]
Thanks! And remember the `npm publish`. :)

**Comment by FredKSchott** [comment]
This will all be streamlined soon :)
