### ISSUE TITLE
display error message when element name does not include a dash

### ISSUE THREAD

**Issue by kaycebasques** [Polymer/polytool#39]
1. polytool init
1. select `element`
1. type `myelement`
1. press `enter` key 

Result: `polytool` correctly rejects the name, but does not indicate why the name was rejected.

Expected: `polytool` rejects the name and prints an error message indicating that the element name was rejected because the custom elements spec requires that element names include a dash

**Comment by FredKSchott** [comment]
This is an issue with the generator, polytool just defers to that.

Moved to https://github.com/PolymerLabs/generator-polymer-init/issues/7
